// These styles apply to every route in the application
import "./globals.css";

export const metadata = {
  title: "Postiva by MATA",
  description: "Generated by MATA",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body>
        <div className="flex justify-center">{children}</div>
      </body>
    </html>
  );
}
