// These styles apply to every route in the application
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Geist } from "next/font/google";

const geist = Geist({
  subsets: ["latin"],
});

export const metadata = {
  title: "Postiva by MATA",
  description: "Generated by MATA",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr" className={geist.className}>
      <body>
        <Navbar />
        <div>{children}</div>
      </body>
    </html>
  );
}
