const offerDefaultsSeed = [
  {
    key: 'salesType',
    label: 'Satış Şekli',
    fieldType: 'multiselect',
    options: ['Peşin', 'Leasing', 'Havale/EFT', 'Kredi Kartı'],
    value: [],
    isEditable: true,
    isVisible: true,
    visibleIn: ['offer', 'proforma', 'contract'],
  },
  {
    key: 'paymentTerms',
    label: 'Ödeme Koşulları',
    fieldType: 'text',
    options: [],
    value: '%50 sipariş onayında peşin, %50 teslimattan önce banka havalesi ile ödenecektir. Fiyatlara KDV dahil değildir.',
    isEditable: true,
    isVisible: true,
    visibleIn: ['offer', 'proforma', 'contract'],
  },
  {
    key: 'deliveryTime',
    label: 'Teslim Süresi',
    fieldType: 'text',
    options: [],
    value: 'Teslim süresi, sipariş onayı ve ön ödemenin alınmasından itibaren başlar. Kesin teslim tarihi sipariş aşamasında yazılı olarak teyit edilecektir.',
    isEditable: true,
    isVisible: true,
    visibleIn: ['offer', 'proforma', 'contract'],
  },
  {
    key: 'deliveryPlace',
    label: 'Teslim Yeri',
    fieldType: 'select',
    options: ['EXW', 'FOB', 'CIF', 'DAP'],
    value: 'EXW',
    isEditable: true,
    isVisible: true,
    visibleIn: ['offer', 'proforma', 'contract'],
  },
  {
    key: 'offerValidity',
    label: 'Teklifin Geçerlilik Süresi',
    fieldType: 'text',
    options: [],
    value: 'Bu teklif, düzenlenme tarihinden itibaren 30 gün süreyle geçerlidir.',
    isEditable: true,
    isVisible: true,
    visibleIn: ['offer', 'proforma'],
  },
  {
    key: 'shipping',
    label: 'Nakliye',
    fieldType: 'text',
    options: [],
    value: 'Nakliye, gümrük, sigorta ve iş yerine taşıma giderleri alıcıya aittir. Teşvik belgenize uygun gümrük muafiyeti sağlanamadığı durumlarda doğacak vergiler alıcı tarafından karşılanır.',
    isEditable: false,
    isVisible: true,
    visibleIn: ['offer', 'proforma', 'contract'],
  },
  {
    key: 'warranty',
    label: 'Garanti',
    fieldType: 'text',
    options: [],
    value: 'Ürünler, montaj ve eğitimin tamamlanıp teslim tutanağının imzalandığı tarihten itibaren 12 ay garanti kapsamındadır. Garanti; kullanım kılavuzuna uygun kullanım koşullarında yedek parça ve işçilik maliyetlerini kapsar. Garanti kapsamındaki servis hizmetleri ücretsiz sağlanır; ancak servis personelinin ulaşım ve konaklama giderleri alıcıya aittir.',
    isEditable: false,
    isVisible: true,
    visibleIn: ['offer', 'contract'],
  },
  {
    key: 'warrantyExclusions',
    label: 'Garanti Kapsamı Dışı',
    fieldType: 'text',
    options: [],
    value: 'Aşağıdaki durumlar garanti kapsamı dışındadır: Kullanıcı hatası veya dikkatsizlikten kaynaklanan arızalar; elektrik dalgalanmaları, voltaj düşümü/artışı gibi harici etkenler; sarf malzemeleri ve normal aşınmaya tabi parçalar; yetkisiz servis tarafından yapılan müdahaleler; üretici onayı alınmadan yapılan yazılım veya donanım değişiklikleri.',
    isEditable: false,
    isVisible: true,
    visibleIn: ['contract'],
  },
  {
    key: 'installation',
    label: 'Kurulum ve Eğitim',
    fieldType: 'text',
    options: [],
    value: 'Kurulum ve operatör eğitimi firmamız teknisyenleri tarafından gerçekleştirilir ve teklif fiyatına dahildir. Standart kurulum ve eğitim süresi 3 iş günüdür. Teknisyenlerimizin şehirlerarası/uluslararası ulaşım, konaklama ve iaşe giderleri alıcıya aittir. Eğitim verilmiş operatörün değişmesi durumunda bu değişiklik tarafımıza bildirilmelidir; aksi hâlde yeni operatör kaynaklı arızalardan firmamız sorumlu tutulamaz.',
    isEditable: false,
    isVisible: true,
    visibleIn: ['offer', 'contract'],
  },
  {
    key: 'serviceTerms',
    label: 'Servis Hizmetleri',
    fieldType: 'text',
    options: [],
    value: 'Garanti süresi sonrasında teknik servis hizmetleri ücretli olarak sağlanmaktadır. Servis talebi yazılı olarak iletilmeli, müdahale süresi ve ücreti tarafımızca onaylandıktan sonra işlem başlatılır. Uzaktan destek ve yerinde servis seçenekleri mevcuttur.',
    isEditable: false,
    isVisible: true,
    visibleIn: ['offer', 'contract'],
  },
  {
    key: 'unauthorizedService',
    label: 'Yetkisiz Servis',
    fieldType: 'text',
    options: [],
    value: 'Garanti süresi boyunca makineye yalnızca yetkili teknik servisimiz tarafından müdahale edilebilir. Üçüncü şahıslar tarafından gerçekleştirilen montaj, demontaj veya teknik müdahaleler garantiyi geçersiz kılar ve doğacak hasarlardan firmamız sorumlu tutulamaz.',
    isEditable: false,
    isVisible: true,
    visibleIn: ['contract'],
  },
  {
    key: 'importantNotes',
    label: 'Önemli Notlar',
    fieldType: 'text',
    options: [],
    value: 'Teklif fiyatlarına KDV, gümrük vergileri ve diğer yasal yükümlülükler dahil değildir. Görseller teklif kapsamında yer almayan opsiyonları içerebilir. Sipariş aşamasında teknik detaylarda yapılacak değişiklikler fiyat revizyonuna neden olabilir. Bu teklifin bir bölümünün veya tamamının üçüncü taraflarla paylaşılması yazılı iznimize tabidir.',
    isEditable: false,
    isVisible: true,
    visibleIn: ['offer', 'contract'],
  },
]

module.exports = offerDefaultsSeed
